name: CI
on: 
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1 
      
    
    - name: Sync repo root to S3 bucket, Continuous Integration of github to AWS s3
      run: aws s3 sync ./ s3://sudodave.dev --delete --exclude ".github/*" --exclude ".git/*" --exclude ".gitignore"
